<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Automatic Construction of Bootstrap Confidence Intervals • bcaboot</title>
<!-- jquery --><script src="https://code.jquery.com/jquery-3.1.0.min.js" integrity="sha384-nrOSfDHtoPMzJHjVTdCopGqIqeYETSXhZDFyniQ8ZHcVy08QesyHcnOUpMpqnmWq" crossorigin="anonymous"></script><!-- Bootstrap --><link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script><!-- Font Awesome icons --><link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-T8Gy5hrqNKT+hzMclPo118YTQO6cYprQmhrYwIiQ/3axmI1hQomh7Ud2hPOy8SP1" crossorigin="anonymous">
<!-- clipboard.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/1.7.1/clipboard.min.js" integrity="sha384-cV+rhyOuRHc9Ub/91rihWcGmMmCXDeksTtCihMupQHSsi8GIIRDG0ThDc3HGQFJ3" crossorigin="anonymous"></script><!-- sticky kit --><script src="https://cdnjs.cloudflare.com/ajax/libs/sticky-kit/1.1.3/sticky-kit.min.js" integrity="sha256-c4Rlo1ZozqTPE2RLuvbusY3+SU1pQaJC0TjuhygMipw=" crossorigin="anonymous"></script><!-- pkgdown --><link href="../pkgdown.css" rel="stylesheet">
<script src="../pkgdown.js"></script><meta property="og:title" content="Automatic Construction of Bootstrap Confidence Intervals">
<meta property="og:description" content="">
<meta name="twitter:card" content="summary">
<!-- mathjax --><script src="https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script><!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
</head>
<body>
    <div class="container template-article">
      <header><div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <span class="navbar-brand">
        <a class="navbar-link" href="../index.html">bcaboot</a>
        <span class="label label-default" data-toggle="tooltip" data-placement="bottom" title="Released package">0.2.1</span>
      </span>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
<li>
  <a href="../index.html">
    <span class="fa fa-home fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="../articles/bcaboot.html">Get started</a>
</li>
<li>
  <a href="../reference/index.html">Reference</a>
</li>
      </ul>
<ul class="nav navbar-nav navbar-right">
<li>
  <a href="https://github.com/bnaras/bcaboot">
    <span class="fa fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
</div>
<!--/.nav-collapse -->
  </div>
<!--/.container -->
</div>
<!--/.navbar -->

      
      </header><div class="row">
  <div class="col-md-9 contents">
    <div class="page-header toc-ignore">
      <h1>Automatic Construction of Bootstrap Confidence Intervals</h1>
                        <h4 class="author">Bradley Efron and Balasubramanian Narasimhan</h4>
            
            <h4 class="date">2018-08-28</h4>
      
      <small class="dont-index">Source: <a href="https://github.com/bnaras/bcaboot/blob/master/vignettes/bcaboot.Rmd"><code>vignettes/bcaboot.Rmd</code></a></small>
      <div class="hidden name"><code>bcaboot.Rmd</code></div>

    </div>

    
    
<div id="introduction" class="section level2">
<h2 class="hasAnchor">
<a href="#introduction" class="anchor"></a>Introduction</h2>
<p>Bootstrap confidence intervals depend on three elements:</p>
<ul>
<li>the cdf of the  bootstrap replications <span class="math inline">\(t_i^*\)</span>, <span class="math inline">\(i=1\ldots B\)</span>
</li>
<li>the bias-correction number <span class="math inline">\(z_0 = \Phi(\sum_i^B I(t_i^* &lt; t_0) / B )\)</span> where <span class="math inline">\(t_0=f(x)\)</span> is the original estimate</li>
<li>the acceleration number <span class="math inline">\(a\)</span> that measures the rate of change in <span class="math inline">\(\sigma_{t_0}\)</span> as <span class="math inline">\(x\)</span>, the data changes.</li>
</ul>
<p>The first two of these depend only on the bootstrap distribution, and not how it is generated: parametrically or non-parametrically.</p>
<p>Package <code>bcaboot</code> aims to make construction of bootstrap confidence intervals <em>almost</em> automatic. The three main functions for the user are:</p>
<ul>
<li>
<code>bcajack</code> and <code>bcajack2</code> for nonparametric bootstrap</li>
<li>
<code>bcapar</code> for parametric bootstrap</li>
</ul>
<p>Further details are in the <span class="citation">Efron and Narasimhan (2018)</span> paper. Much of the theory behind the approach can be found in references <span class="citation">Efron (1987)</span>, <span class="citation">DiCiccio and Efron (1992)</span>, <span class="citation">DiCiccio and Efron (1996)</span>, and <span class="citation">Efron and Hastie (2016)</span>.</p>
</div>
<div id="a-nonparametric-example" class="section level2">
<h2 class="hasAnchor">
<a href="#a-nonparametric-example" class="anchor"></a>A Nonparametric Example</h2>
<p>Suppose we wish to construct bootstrap confidence intervals for an <span class="math inline">\(R^2\)</span>-statistic from a linear regression. Using the diabetes data from the <a href="https://cran.r-project.org/package=lars"><code>lars</code></a> (442 by 11) as an example, we use the function below to regress the <code>y</code> on <code>x</code>, a matrix of of 10 predictors, to compute <span class="math inline">\(R^2\)</span>.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb1-1" data-line-number="1"><span class="kw">data</span>(diabetes, <span class="dt">package =</span> <span class="st">"bcaboot"</span>)</a>
<a class="sourceLine" id="cb1-2" data-line-number="2">Xy &lt;-<span class="st"> </span><span class="kw">cbind</span>(diabetes<span class="op">$</span>x, diabetes<span class="op">$</span>y)</a>
<a class="sourceLine" id="cb1-3" data-line-number="3">rfun &lt;-<span class="st"> </span><span class="cf">function</span>(Xy) {</a>
<a class="sourceLine" id="cb1-4" data-line-number="4">    y &lt;-<span class="st"> </span>Xy[, <span class="dv">11</span>]</a>
<a class="sourceLine" id="cb1-5" data-line-number="5">    X &lt;-<span class="st"> </span>Xy[, <span class="dv">1</span><span class="op">:</span><span class="dv">10</span>]</a>
<a class="sourceLine" id="cb1-6" data-line-number="6">    <span class="kw">summary</span>(<span class="kw">lm</span>(y <span class="op">~</span><span class="st"> </span>X) )<span class="op">$</span>adj.r.squared</a>
<a class="sourceLine" id="cb1-7" data-line-number="7">}</a></code></pre></div>
<p>Constructing bootstrap confidence intervals involves merely calling <code>bcajack</code>:</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb2-1" data-line-number="1"><span class="kw">set.seed</span>(<span class="dv">1234</span>)</a>
<a class="sourceLine" id="cb2-2" data-line-number="2">result &lt;-<span class="st"> </span><span class="kw"><a href="../reference/bcajack.html">bcajack</a></span>(<span class="dt">x =</span> Xy, <span class="dt">B =</span> <span class="dv">2000</span>, <span class="dt">func =</span> rfun, <span class="dt">verbose =</span> <span class="ot">FALSE</span>)</a></code></pre></div>
<p>The <code>result</code> contains several components. The confidence interval limits can be obtained via</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb3-1" data-line-number="1">knitr<span class="op">::</span><span class="kw"><a href="http://www.rdocumentation.org/packages/knitr/topics/kable">kable</a></span>(result<span class="op">$</span>lims, <span class="dt">digits =</span> <span class="dv">3</span>)</a></code></pre></div>
<table class="table">
<thead><tr class="header">
<th></th>
<th align="right">bca</th>
<th align="right">jacksd</th>
<th align="right">std</th>
<th align="right">pct</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>0.025</td>
<td align="right">0.437</td>
<td align="right">0.004</td>
<td align="right">0.444</td>
<td align="right">0.006</td>
</tr>
<tr class="even">
<td>0.05</td>
<td align="right">0.446</td>
<td align="right">0.003</td>
<td align="right">0.454</td>
<td align="right">0.013</td>
</tr>
<tr class="odd">
<td>0.1</td>
<td align="right">0.457</td>
<td align="right">0.002</td>
<td align="right">0.466</td>
<td align="right">0.032</td>
</tr>
<tr class="even">
<td>0.16</td>
<td align="right">0.465</td>
<td align="right">0.003</td>
<td align="right">0.475</td>
<td align="right">0.060</td>
</tr>
<tr class="odd">
<td>0.5</td>
<td align="right">0.498</td>
<td align="right">0.001</td>
<td align="right">0.507</td>
<td align="right">0.293</td>
</tr>
<tr class="even">
<td>0.84</td>
<td align="right">0.529</td>
<td align="right">0.002</td>
<td align="right">0.538</td>
<td align="right">0.672</td>
</tr>
<tr class="odd">
<td>0.9</td>
<td align="right">0.540</td>
<td align="right">0.002</td>
<td align="right">0.547</td>
<td align="right">0.768</td>
</tr>
<tr class="even">
<td>0.95</td>
<td align="right">0.550</td>
<td align="right">0.002</td>
<td align="right">0.559</td>
<td align="right">0.862</td>
</tr>
<tr class="odd">
<td>0.975</td>
<td align="right">0.560</td>
<td align="right">0.002</td>
<td align="right">0.569</td>
<td align="right">0.918</td>
</tr>
</tbody>
</table>
<p>The first column shows the estimated Bca confidence limits at the requested alpha percentiles which can be compared with the standard limits <span class="math inline">\(\theta \pm \hat{\sigma}z_{\alpha}\)</span> under the column titled <code>standard</code>. The <code>jacksd</code> column jacksd gives the internal standard errors for the Bca limits, quite small in this example. The <code>pct</code> column gives percentiles of the ordered <code>B</code> bootstrap replications corresponding to the Bca limits, e.g. the 91.85 percentile equals the the .975 Bca limit .5600968.</p>
<p>Further details are provided by the <code>stats</code> component.</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb4-1" data-line-number="1">knitr<span class="op">::</span><span class="kw"><a href="http://www.rdocumentation.org/packages/knitr/topics/kable">kable</a></span>(result<span class="op">$</span>stats, <span class="dt">digits =</span> <span class="dv">3</span>)</a></code></pre></div>
<table class="table">
<thead><tr class="header">
<th></th>
<th align="right">theta</th>
<th align="right">sdboot</th>
<th align="right">z0</th>
<th align="right">a</th>
<th align="right">sdjack</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>est</td>
<td align="right">0.507</td>
<td align="right">0.032</td>
<td align="right">-0.272</td>
<td align="right">-0.007</td>
<td align="right">0.033</td>
</tr>
<tr class="even">
<td>jsd</td>
<td align="right">0.000</td>
<td align="right">0.000</td>
<td align="right">0.030</td>
<td align="right">0.000</td>
<td align="right">0.000</td>
</tr>
</tbody>
</table>
<p>The first column <code>theta</code> is the original point estimate of the parameter of interest, <code>sdboot</code> is its bootstrap estimate of standard error. The quantity <code>z0</code> is the Bca bias correction value, in this case quite negative; <code>a</code> is the acceleration, a component of the Bca limits (nearly zero here). Finally, <code>sdjack</code> is the jackknife estimate of standard error for <code>theta</code>.</p>
<p>The bottom line gives the internal standard errors for the five quantities above. This is substantial for <code>z0</code> above.</p>
<p>The resulting object can be plotted using <code>bcaplot</code>.</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb5-1" data-line-number="1"><span class="kw"><a href="../reference/bcaplot.html">bcaplot</a></span>(result)</a></code></pre></div>
<p><img src="bcaboot_files/figure-html/unnamed-chunk-6-1.png" width="700"></p>
</div>
<div id="a-parametric-example" class="section level2">
<h2 class="hasAnchor">
<a href="#a-parametric-example" class="anchor"></a>A Parametric Example</h2>
<p>A logistic regression was fit to data on 812 neonates at a large clinic. Here is a summary of the dataset.</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb6-1" data-line-number="1"><span class="kw">str</span>(neonates)</a></code></pre></div>
<pre><code>## 'data.frame':    812 obs. of  12 variables:
##  $ gest: num  -0.729 -0.729 1.156 -2.884 0.348 ...
##  $ ap  : num  0.856 0.856 0.856 -2.076 0.856 ...
##  $ bwei: num  -0.694 -0.694 0.786 -2.174 0.786 ...
##  $ gen : num  1.227 -0.814 -0.814 1.227 -0.814 ...
##  $ resp: num  0.78 -0.939 1.639 1.639 1.639 ...
##  $ head: num  -0.402 -0.402 -0.402 -0.402 -0.402 ...
##  $ hr  : num  -0.256 -0.256 -0.256 -0.256 -0.256 ...
##  $ cpap: num  1.866 -0.535 1.866 1.866 1.866 ...
##  $ age : num  -0.94 -0.94 -0.94 -0.94 1.06 ...
##  $ temp: num  -0.669 -0.669 -0.669 -0.669 2.339 ...
##  $ size: num  0.484 -1.319 -1.319 0.484 0.484 ...
##  $ y   : int  1 1 1 1 1 1 1 1 1 1 ...</code></pre>
<p>The goal was to predict death versus survival—<span class="math inline">\(y\)</span> is 1 or 0, respectively—on the basis of 11 baseline variables of which one of them <code>resp</code> was of particular concern. (There were 207 deaths and 605 survivors.) So here <span class="math inline">\(\theta\)</span>, the parameter of interest is the coefficient of <code>resp</code>. Discussions with the investigator suggested a weighting of 4 to 1 of deaths versus non-deaths.</p>
<div id="a-logistic-model" class="section level3">
<h3 class="hasAnchor">
<a href="#a-logistic-model" class="anchor"></a>A Logistic Model</h3>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb8-1" data-line-number="1">weights &lt;-<span class="st"> </span><span class="kw">with</span>(neonates, <span class="kw">ifelse</span>(y <span class="op">==</span><span class="st"> </span><span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">4</span>))</a>
<a class="sourceLine" id="cb8-2" data-line-number="2">glm_model &lt;-<span class="st"> </span><span class="kw">glm</span>(<span class="dt">formula =</span> y <span class="op">~</span><span class="st"> </span>., <span class="dt">family =</span> <span class="st">"binomial"</span>, <span class="dt">weights =</span> weights, <span class="dt">data =</span> neonates)</a>
<a class="sourceLine" id="cb8-3" data-line-number="3"><span class="kw">summary</span>(glm_model)</a></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = y ~ ., family = "binomial", data = neonates, weights = weights)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -3.0338  -0.9211  -0.5607   0.1697   3.9021  
## 
## Coefficients:
##             Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept) -0.26510    0.07598  -3.489 0.000485 ***
## gest        -0.70602    0.13117  -5.383 7.35e-08 ***
## ap          -0.78594    0.07874  -9.982  &lt; 2e-16 ***
## bwei        -0.23332    0.12592  -1.853 0.063879 .  
## gen         -0.04107    0.07355  -0.558 0.576594    
## resp         0.94306    0.08974  10.509  &lt; 2e-16 ***
## head         0.04813    0.08057   0.597 0.550299    
## hr           0.03504    0.07191   0.487 0.626045    
## cpap         0.43438    0.08869   4.898 9.70e-07 ***
## age          0.15727    0.08492   1.852 0.064041 .  
## temp        -0.05960    0.08506  -0.701 0.483520    
## size        -0.37477    0.09919  -3.778 0.000158 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 1951.7  on 811  degrees of freedom
## Residual deviance: 1187.2  on 800  degrees of freedom
## AIC: 1211.2
## 
## Number of Fisher Scoring iterations: 5</code></pre>
<p>Parametric bootstrapping in this context requires us to independently sample the response according to the estimated probabilities from regression model. As discussed in the paper accompanying this software, routine <code>bcapar</code> also requires sufficient statistics <span class="math inline">\(\hat{\beta} = M^\prime y\)</span> where <span class="math inline">\(M\)</span> is the model matrix. Therefore, it makes sense to have a function do the work. The function <code>glm_boot</code> below returns a list of the estimate <span class="math inline">\(\hat{\theta}\)</span>, the bootstrap estimates, and the sufficient statistics.</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb10-1" data-line-number="1">glm_boot &lt;-<span class="st"> </span><span class="cf">function</span>(B, glm_model, weights, <span class="dt">var =</span> <span class="st">"resp"</span>) {</a>
<a class="sourceLine" id="cb10-2" data-line-number="2">    pi_hat &lt;-<span class="st"> </span>glm_model<span class="op">$</span>fitted.values</a>
<a class="sourceLine" id="cb10-3" data-line-number="3">    n &lt;-<span class="st"> </span><span class="kw">length</span>(pi_hat)</a>
<a class="sourceLine" id="cb10-4" data-line-number="4">    y_star &lt;-<span class="st"> </span><span class="kw">sapply</span>(<span class="kw">seq_len</span>(B), <span class="cf">function</span>(i) <span class="kw">ifelse</span>(<span class="kw">runif</span>(n) <span class="op">&lt;=</span><span class="st"> </span>pi_hat, <span class="dv">1</span>, <span class="dv">0</span>))</a>
<a class="sourceLine" id="cb10-5" data-line-number="5">    beta_star &lt;-<span class="st"> </span><span class="kw">apply</span>(y_star, <span class="dv">2</span>, <span class="cf">function</span>(y) {</a>
<a class="sourceLine" id="cb10-6" data-line-number="6">        boot_data &lt;-<span class="st"> </span>glm_model<span class="op">$</span>data</a>
<a class="sourceLine" id="cb10-7" data-line-number="7">        boot_data<span class="op">$</span>y &lt;-<span class="st"> </span>y</a>
<a class="sourceLine" id="cb10-8" data-line-number="8">        <span class="kw">coef</span>(<span class="kw">glm</span>(<span class="dt">formula =</span> y <span class="op">~</span><span class="st"> </span>., <span class="dt">data =</span> boot_data, <span class="dt">weights =</span> weights, <span class="dt">family =</span> <span class="st">"binomial"</span>))</a>
<a class="sourceLine" id="cb10-9" data-line-number="9">    })</a>
<a class="sourceLine" id="cb10-10" data-line-number="10">    <span class="kw">list</span>(<span class="dt">theta =</span> <span class="kw">coef</span>(glm_model)[var],</a>
<a class="sourceLine" id="cb10-11" data-line-number="11">         <span class="dt">theta_star =</span> beta_star[var, ],</a>
<a class="sourceLine" id="cb10-12" data-line-number="12">         <span class="dt">suff_stat =</span> <span class="kw">t</span>(y_star) <span class="op">%*%</span><span class="st"> </span><span class="kw">model.matrix</span>(glm_model))</a>
<a class="sourceLine" id="cb10-13" data-line-number="13">}</a></code></pre></div>
<p>Now we can compute the bootstrap estimates using <code>bcapar</code>.</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb11-1" data-line-number="1"><span class="kw">set.seed</span>(<span class="dv">3891</span>)</a>
<a class="sourceLine" id="cb11-2" data-line-number="2">glm_boot_out &lt;-<span class="st"> </span><span class="kw">glm_boot</span>(<span class="dt">B =</span> <span class="dv">2000</span>, <span class="dt">glm_model =</span> glm_model, <span class="dt">weights =</span> weights)</a>
<a class="sourceLine" id="cb11-3" data-line-number="3">glm_bca &lt;-<span class="st"> </span><span class="kw"><a href="../reference/bcapar.html">bcapar</a></span>(<span class="dt">t0 =</span> glm_boot_out<span class="op">$</span>theta,</a>
<a class="sourceLine" id="cb11-4" data-line-number="4">                  <span class="dt">tt =</span> glm_boot_out<span class="op">$</span>theta_star,</a>
<a class="sourceLine" id="cb11-5" data-line-number="5">                  <span class="dt">bb =</span> glm_boot_out<span class="op">$</span>suff_stat)</a></code></pre></div>
<p>We can examine the bootstrap limits and statistics.</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb12-1" data-line-number="1">knitr<span class="op">::</span><span class="kw"><a href="http://www.rdocumentation.org/packages/knitr/topics/kable">kable</a></span>(glm_bca<span class="op">$</span>lims, <span class="dt">digits =</span> <span class="dv">3</span>)</a></code></pre></div>
<table class="table">
<thead><tr class="header">
<th></th>
<th align="right">bca</th>
<th align="right">jacksd</th>
<th align="right">pct</th>
<th align="right">std</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>0.025</td>
<td align="right">0.598</td>
<td align="right">0.023</td>
<td align="right">0.006</td>
<td align="right">0.639</td>
</tr>
<tr class="even">
<td>0.05</td>
<td align="right">0.655</td>
<td align="right">0.016</td>
<td align="right">0.016</td>
<td align="right">0.688</td>
</tr>
<tr class="odd">
<td>0.1</td>
<td align="right">0.717</td>
<td align="right">0.009</td>
<td align="right">0.040</td>
<td align="right">0.745</td>
</tr>
<tr class="even">
<td>0.16</td>
<td align="right">0.764</td>
<td align="right">0.006</td>
<td align="right">0.073</td>
<td align="right">0.789</td>
</tr>
<tr class="odd">
<td>0.5</td>
<td align="right">0.913</td>
<td align="right">0.004</td>
<td align="right">0.333</td>
<td align="right">0.943</td>
</tr>
<tr class="even">
<td>0.84</td>
<td align="right">1.067</td>
<td align="right">0.004</td>
<td align="right">0.710</td>
<td align="right">1.097</td>
</tr>
<tr class="odd">
<td>0.9</td>
<td align="right">1.114</td>
<td align="right">0.009</td>
<td align="right">0.797</td>
<td align="right">1.142</td>
</tr>
<tr class="even">
<td>0.95</td>
<td align="right">1.168</td>
<td align="right">0.008</td>
<td align="right">0.880</td>
<td align="right">1.198</td>
</tr>
<tr class="odd">
<td>0.975</td>
<td align="right">1.214</td>
<td align="right">0.010</td>
<td align="right">0.930</td>
<td align="right">1.247</td>
</tr>
</tbody>
</table>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb13-1" data-line-number="1">knitr<span class="op">::</span><span class="kw"><a href="http://www.rdocumentation.org/packages/knitr/topics/kable">kable</a></span>(glm_bca<span class="op">$</span>stats, <span class="dt">digits =</span> <span class="dv">3</span>)</a></code></pre></div>
<table class="table">
<thead><tr class="header">
<th></th>
<th align="right">theta</th>
<th align="right">sd</th>
<th align="right">a</th>
<th align="right">az</th>
<th align="right">z0</th>
<th align="right">A</th>
<th align="right">sdd</th>
<th align="right">mean</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>est</td>
<td align="right">0.943</td>
<td align="right">0.155</td>
<td align="right">-0.019</td>
<td align="right">-0.001</td>
<td align="right">-0.215</td>
<td align="right">0.006</td>
<td align="right">0.129</td>
<td align="right">0.982</td>
</tr>
<tr class="even">
<td>jsd</td>
<td align="right">0.000</td>
<td align="right">0.002</td>
<td align="right">0.008</td>
<td align="right">0.012</td>
<td align="right">0.024</td>
<td align="right">0.024</td>
<td align="right">0.004</td>
<td align="right">0.003</td>
</tr>
</tbody>
</table>
<p>Our bootstrap standard error using <span class="math inline">\(B=2000\)</span> samples for <code>resp</code> can be read off from the last table as <span class="math inline">\(0.943\pm 0.155\)</span>. We can also see a small upward bias from the fact that 0.585 proportion of bootstrap replicates were above <span class="math inline">\(0.943\)</span>. This is also reflected in the bias-corrector term <span class="math inline">\(\hat{z}_0= -0.215\)</span> in the table above with an internal standard error of $0.024.</p>
</div>
<div id="a-penalized-logistic-model" class="section level3">
<h3 class="hasAnchor">
<a href="#a-penalized-logistic-model" class="anchor"></a>A Penalized Logistic Model</h3>
<p>Now suppose we wish to use a nonstandard estimation procedure, for example, via the <code>glmnet</code> package, which uses cross-validation to figure out a best fit, corresponding to a penalization parameter <span class="math inline">\(\lambda\)</span> (named <code>lambda.min</code>).</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb14-1" data-line-number="1">X &lt;-<span class="st"> </span><span class="kw">as.matrix</span>(neonates[, <span class="kw">seq_len</span>(<span class="dv">11</span>)]) ; Y &lt;-<span class="st"> </span>neonates<span class="op">$</span>y;</a>
<a class="sourceLine" id="cb14-2" data-line-number="2">glmnet_model &lt;-<span class="st"> </span>glmnet<span class="op">::</span><span class="kw"><a href="http://www.rdocumentation.org/packages/glmnet/topics/cv.glmnet">cv.glmnet</a></span>(<span class="dt">x =</span> X, <span class="dt">y =</span> Y, <span class="dt">family =</span> <span class="st">"binomial"</span>, <span class="dt">weights =</span> weights)</a></code></pre></div>
<p>We can examine the estimates at the <code>lambda.min</code> as follows.</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb15-1" data-line-number="1">coefs &lt;-<span class="st"> </span><span class="kw">as.matrix</span>(<span class="kw">coef</span>(glmnet_model, <span class="dt">s =</span> glmnet_model<span class="op">$</span>lambda.min))</a>
<a class="sourceLine" id="cb15-2" data-line-number="2">knitr<span class="op">::</span><span class="kw"><a href="http://www.rdocumentation.org/packages/knitr/topics/kable">kable</a></span>(<span class="kw">data.frame</span>(<span class="dt">variable =</span> <span class="kw">rownames</span>(coefs), <span class="dt">coefficient =</span> coefs[, <span class="dv">1</span>]), <span class="dt">row.names =</span> <span class="ot">FALSE</span>, <span class="dt">digits =</span> <span class="dv">3</span>)</a></code></pre></div>
<table class="table">
<thead><tr class="header">
<th align="left">variable</th>
<th align="right">coefficient</th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="left">(Intercept)</td>
<td align="right">-0.208</td>
</tr>
<tr class="even">
<td align="left">gest</td>
<td align="right">-0.524</td>
</tr>
<tr class="odd">
<td align="left">ap</td>
<td align="right">-0.678</td>
</tr>
<tr class="even">
<td align="left">bwei</td>
<td align="right">-0.272</td>
</tr>
<tr class="odd">
<td align="left">gen</td>
<td align="right">0.000</td>
</tr>
<tr class="even">
<td align="left">resp</td>
<td align="right">0.862</td>
</tr>
<tr class="odd">
<td align="left">head</td>
<td align="right">0.000</td>
</tr>
<tr class="even">
<td align="left">hr</td>
<td align="right">0.000</td>
</tr>
<tr class="odd">
<td align="left">cpap</td>
<td align="right">0.378</td>
</tr>
<tr class="even">
<td align="left">age</td>
<td align="right">0.042</td>
</tr>
<tr class="odd">
<td align="left">temp</td>
<td align="right">0.000</td>
</tr>
<tr class="even">
<td align="left">size</td>
<td align="right">-0.208</td>
</tr>
</tbody>
</table>
<p>Following the lines above, we create a helper function to perform the bootstrap.</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb16-1" data-line-number="1">glmnet_boot &lt;-<span class="st"> </span><span class="cf">function</span>(B, X, y, glmnet_model, weights, <span class="dt">var =</span> <span class="st">"resp"</span>) {</a>
<a class="sourceLine" id="cb16-2" data-line-number="2">    lambda &lt;-<span class="st"> </span>glmnet_model<span class="op">$</span>lambda.min</a>
<a class="sourceLine" id="cb16-3" data-line-number="3">    theta &lt;-<span class="st"> </span><span class="kw">as.matrix</span>(<span class="kw">coef</span>(glmnet_model, <span class="dt">s =</span> lambda))</a>
<a class="sourceLine" id="cb16-4" data-line-number="4">    pi_hat &lt;-<span class="st"> </span><span class="kw">predict</span>(glmnet_model, <span class="dt">newx =</span> X, <span class="dt">s =</span> <span class="st">"lambda.min"</span>, <span class="dt">type =</span> <span class="st">"response"</span>)</a>
<a class="sourceLine" id="cb16-5" data-line-number="5">    n &lt;-<span class="st"> </span><span class="kw">length</span>(pi_hat)</a>
<a class="sourceLine" id="cb16-6" data-line-number="6">    y_star &lt;-<span class="st"> </span><span class="kw">sapply</span>(<span class="kw">seq_len</span>(B), <span class="cf">function</span>(i) <span class="kw">ifelse</span>(<span class="kw">runif</span>(n) <span class="op">&lt;=</span><span class="st"> </span>pi_hat, <span class="dv">1</span>, <span class="dv">0</span>))</a>
<a class="sourceLine" id="cb16-7" data-line-number="7">    beta_star &lt;-<span class="st"> </span><span class="kw">apply</span>(y_star, <span class="dv">2</span>,</a>
<a class="sourceLine" id="cb16-8" data-line-number="8">                       <span class="cf">function</span>(y) {</a>
<a class="sourceLine" id="cb16-9" data-line-number="9">                           <span class="kw">as.matrix</span>(<span class="kw">coef</span>(glmnet<span class="op">::</span><span class="kw"><a href="http://www.rdocumentation.org/packages/glmnet/topics/glmnet">glmnet</a></span>(<span class="dt">x =</span> X, <span class="dt">y =</span> y, <span class="dt">lambda =</span> lambda, <span class="dt">weights =</span> weights, <span class="dt">family =</span> <span class="st">"binomial"</span>)))</a>
<a class="sourceLine" id="cb16-10" data-line-number="10">                       })</a>
<a class="sourceLine" id="cb16-11" data-line-number="11"></a>
<a class="sourceLine" id="cb16-12" data-line-number="12">    <span class="kw">rownames</span>(beta_star) &lt;-<span class="st"> </span><span class="kw">rownames</span>(theta)</a>
<a class="sourceLine" id="cb16-13" data-line-number="13">    <span class="kw">list</span>(<span class="dt">theta =</span> theta[var, ],</a>
<a class="sourceLine" id="cb16-14" data-line-number="14">         <span class="dt">theta_star =</span> beta_star[var, ],</a>
<a class="sourceLine" id="cb16-15" data-line-number="15">         <span class="dt">suff_stat =</span> <span class="kw">t</span>(y_star) <span class="op">%*%</span><span class="st"> </span>X)</a>
<a class="sourceLine" id="cb16-16" data-line-number="16">}</a></code></pre></div>
<p>And off we go.</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb17-1" data-line-number="1">glmnet_boot_out &lt;-<span class="st"> </span><span class="kw">glmnet_boot</span>(<span class="dt">B =</span> <span class="dv">2000</span>, X, y, glmnet_model, weights)</a>
<a class="sourceLine" id="cb17-2" data-line-number="2">glmnet_bca &lt;-<span class="st"> </span><span class="kw"><a href="../reference/bcapar.html">bcapar</a></span>(<span class="dt">t0 =</span> glmnet_boot_out<span class="op">$</span>theta,</a>
<a class="sourceLine" id="cb17-3" data-line-number="3">                     <span class="dt">tt =</span> glmnet_boot_out<span class="op">$</span>theta_star,</a>
<a class="sourceLine" id="cb17-4" data-line-number="4">                     <span class="dt">bb =</span> glmnet_boot_out<span class="op">$</span>suff_stat)</a></code></pre></div>
<p>We can compare the output of this against what we got from <code>glm</code> above.</p>
<p>We can examine the bootstrap limits and statistics.</p>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb18-1" data-line-number="1">knitr<span class="op">::</span><span class="kw"><a href="http://www.rdocumentation.org/packages/knitr/topics/kable">kable</a></span>(glmnet_bca<span class="op">$</span>lims, <span class="dt">digits =</span> <span class="dv">3</span>)</a></code></pre></div>
<table class="table">
<thead><tr class="header">
<th></th>
<th align="right">bca</th>
<th align="right">jacksd</th>
<th align="right">pct</th>
<th align="right">std</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>0.025</td>
<td align="right">0.667</td>
<td align="right">0.009</td>
<td align="right">0.123</td>
<td align="right">0.613</td>
</tr>
<tr class="even">
<td>0.05</td>
<td align="right">0.707</td>
<td align="right">0.008</td>
<td align="right">0.201</td>
<td align="right">0.653</td>
</tr>
<tr class="odd">
<td>0.1</td>
<td align="right">0.750</td>
<td align="right">0.007</td>
<td align="right">0.320</td>
<td align="right">0.699</td>
</tr>
<tr class="even">
<td>0.16</td>
<td align="right">0.789</td>
<td align="right">0.006</td>
<td align="right">0.430</td>
<td align="right">0.736</td>
</tr>
<tr class="odd">
<td>0.5</td>
<td align="right">0.915</td>
<td align="right">0.006</td>
<td align="right">0.794</td>
<td align="right">0.862</td>
</tr>
<tr class="even">
<td>0.84</td>
<td align="right">1.034</td>
<td align="right">0.005</td>
<td align="right">0.964</td>
<td align="right">0.988</td>
</tr>
<tr class="odd">
<td>0.9</td>
<td align="right">1.076</td>
<td align="right">0.013</td>
<td align="right">0.981</td>
<td align="right">1.025</td>
</tr>
<tr class="even">
<td>0.95</td>
<td align="right">1.129</td>
<td align="right">0.016</td>
<td align="right">0.992</td>
<td align="right">1.071</td>
</tr>
<tr class="odd">
<td>0.975</td>
<td align="right">1.176</td>
<td align="right">0.031</td>
<td align="right">0.997</td>
<td align="right">1.111</td>
</tr>
</tbody>
</table>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb19-1" data-line-number="1">knitr<span class="op">::</span><span class="kw"><a href="http://www.rdocumentation.org/packages/knitr/topics/kable">kable</a></span>(glmnet_bca<span class="op">$</span>stats, <span class="dt">digits =</span> <span class="dv">3</span>)</a></code></pre></div>
<table class="table">
<thead><tr class="header">
<th></th>
<th align="right">theta</th>
<th align="right">sd</th>
<th align="right">a</th>
<th align="right">az</th>
<th align="right">z0</th>
<th align="right">A</th>
<th align="right">sdd</th>
<th align="right">mean</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>est</td>
<td align="right">0.862</td>
<td align="right">0.127</td>
<td align="right">-0.009</td>
<td align="right">-0.025</td>
<td align="right">0.411</td>
<td align="right">-0.006</td>
<td align="right">0.108</td>
<td align="right">0.811</td>
</tr>
<tr class="even">
<td>jsd</td>
<td align="right">0.000</td>
<td align="right">0.002</td>
<td align="right">0.011</td>
<td align="right">0.013</td>
<td align="right">0.028</td>
<td align="right">0.032</td>
<td align="right">0.005</td>
<td align="right">0.002</td>
</tr>
</tbody>
</table>
<p>The shrinkage is evident; we now have the bootstrap estimate is now <span class="math inline">\(0.862\pm 0.127\)</span>. In fact, we now have only 0.3405 proportion of bootstrap replicates above <span class="math inline">\(0.862\)</span>. Therefore, the bias corrector is large: <span class="math inline">\(\hat{z}_0 = 0.411.\)</span></p>
<p>Finally, we can plot both the <code>glm</code> and <code>glmnet</code> results side-by-side.</p>
<p><img src="bcaboot_files/figure-html/unnamed-chunk-20-1.png" width="700"></p>
</div>
</div>
<div id="ratio-of-independent-variance-estimates" class="section level2">
<h2 class="hasAnchor">
<a href="#ratio-of-independent-variance-estimates" class="anchor"></a>Ratio of Independent Variance Estimates</h2>
<p>Assume we have two independent estimates of variance from normal theory:</p>
<p><span class="math display">\[
\hat{\sigma}_1^2\sim\frac{\sigma_1^2\chi_{n_1}^2}{n_1},
\]</span></p>
<p>and</p>
<p><span class="math display">\[
\hat{\sigma}_2^2\sim\frac{\sigma_2^2\chi_{n_2}^2}{n_2}.
\]</span></p>
<p>Suppose now that our parameter of interest is</p>
<p><span class="math display">\[
    \theta=\frac{\sigma_1^2}{\sigma_2^2}
\]</span></p>
<p>for which we wish to compute confidence limits. In this setting, theory yields exact limits:</p>
<p><span class="math display">\[
\hat{\theta}(\alpha) = \frac{\hat{\theta}}{F_{n_1,n_2}^{1-\alpha}}.
\]</span></p>
<p>We can apply <code>bcapar</code> to this problem. As before, here are our helper functions.</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb20-1" data-line-number="1">ratio_boot &lt;-<span class="st"> </span><span class="cf">function</span>(B, v1, v2) {</a>
<a class="sourceLine" id="cb20-2" data-line-number="2">    s1 &lt;-<span class="st"> </span><span class="kw">sqrt</span>(v1) <span class="op">*</span><span class="st"> </span><span class="kw">rchisq</span>(<span class="dt">n =</span> B, <span class="dt">df =</span> n1)  <span class="op">/</span><span class="st"> </span>n1</a>
<a class="sourceLine" id="cb20-3" data-line-number="3">    s2 &lt;-<span class="st"> </span><span class="kw">sqrt</span>(v2) <span class="op">*</span><span class="st"> </span><span class="kw">rchisq</span>(<span class="dt">n =</span> B, <span class="dt">df =</span> n2)  <span class="op">/</span><span class="st"> </span>n2</a>
<a class="sourceLine" id="cb20-4" data-line-number="4">    theta_star &lt;-<span class="st"> </span>s1 <span class="op">/</span><span class="st"> </span>s2</a>
<a class="sourceLine" id="cb20-5" data-line-number="5">    beta_star &lt;-<span class="st"> </span><span class="kw">cbind</span>(s1, s2)</a>
<a class="sourceLine" id="cb20-6" data-line-number="6">    <span class="kw">list</span>(<span class="dt">theta =</span> v1 <span class="op">/</span><span class="st"> </span>v2,</a>
<a class="sourceLine" id="cb20-7" data-line-number="7">         <span class="dt">theta_star =</span> theta_star,</a>
<a class="sourceLine" id="cb20-8" data-line-number="8">         <span class="dt">suff_stat =</span> beta_star)</a>
<a class="sourceLine" id="cb20-9" data-line-number="9">}</a>
<a class="sourceLine" id="cb20-10" data-line-number="10"></a>
<a class="sourceLine" id="cb20-11" data-line-number="11">funcF &lt;-<span class="st"> </span><span class="cf">function</span>(beta) {</a>
<a class="sourceLine" id="cb20-12" data-line-number="12">    beta[<span class="dv">1</span>] <span class="op">/</span><span class="st"> </span>beta[<span class="dv">2</span>]</a>
<a class="sourceLine" id="cb20-13" data-line-number="13">}</a></code></pre></div>
<p>Note that we have an additional function <code>funcF</code> which corresponds to <span class="math inline">\(\tau(\hat{\beta}^*)\)</span> in the paper. This is the function expressing the parameter of interest as as a function of the sample.</p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb21-1" data-line-number="1">B &lt;-<span class="st"> </span><span class="dv">16000</span>; n1 &lt;-<span class="st"> </span><span class="dv">10</span>; n2 &lt;-<span class="st"> </span><span class="dv">42</span></a>
<a class="sourceLine" id="cb21-2" data-line-number="2">ratio_boot_out &lt;-<span class="st"> </span><span class="kw">ratio_boot</span>(B, <span class="dv">1</span>, <span class="dv">1</span>)</a>
<a class="sourceLine" id="cb21-3" data-line-number="3">result &lt;-<span class="st"> </span><span class="kw"><a href="../reference/bcapar.html">bcapar</a></span>(<span class="dt">t0 =</span> ratio_boot_out<span class="op">$</span>theta,</a>
<a class="sourceLine" id="cb21-4" data-line-number="4">                 <span class="dt">tt =</span> ratio_boot_out<span class="op">$</span>theta_star,</a>
<a class="sourceLine" id="cb21-5" data-line-number="5">                 <span class="dt">bb =</span> ratio_boot_out<span class="op">$</span>suff_stat, <span class="dt">func =</span> funcF)</a></code></pre></div>
<p>The limits obtained are shown below, along with the exact limits as the last column.</p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb22-1" data-line-number="1">exact &lt;-<span class="st"> </span><span class="dv">1</span> <span class="op">/</span><span class="st"> </span><span class="kw">qf</span>(<span class="dt">df1 =</span> n1, <span class="dt">df2 =</span> n2, <span class="dt">p =</span> <span class="dv">1</span> <span class="op">-</span><span class="st"> </span><span class="kw">as.numeric</span>(<span class="kw">rownames</span>(result<span class="op">$</span>lims)))</a>
<a class="sourceLine" id="cb22-2" data-line-number="2">knitr<span class="op">::</span><span class="kw"><a href="http://www.rdocumentation.org/packages/knitr/topics/kable">kable</a></span>(<span class="kw">cbind</span>(result<span class="op">$</span>lims, <span class="dt">exact =</span> exact), <span class="dt">digits =</span> <span class="dv">3</span>)</a></code></pre></div>
<table class="table">
<thead><tr class="header">
<th></th>
<th align="right">bca</th>
<th align="right">jacksd</th>
<th align="right">pct</th>
<th align="right">std</th>
<th align="right">abc</th>
<th align="right">exact</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>0.025</td>
<td align="right">0.416</td>
<td align="right">0.007</td>
<td align="right">0.067</td>
<td align="right">-0.054</td>
<td align="right">0.396</td>
<td align="right">0.422</td>
</tr>
<tr class="even">
<td>0.05</td>
<td align="right">0.477</td>
<td align="right">0.006</td>
<td align="right">0.103</td>
<td align="right">0.116</td>
<td align="right">0.465</td>
<td align="right">0.484</td>
</tr>
<tr class="odd">
<td>0.1</td>
<td align="right">0.562</td>
<td align="right">0.005</td>
<td align="right">0.164</td>
<td align="right">0.311</td>
<td align="right">0.557</td>
<td align="right">0.570</td>
</tr>
<tr class="even">
<td>0.16</td>
<td align="right">0.639</td>
<td align="right">0.008</td>
<td align="right">0.230</td>
<td align="right">0.465</td>
<td align="right">0.642</td>
<td align="right">0.650</td>
</tr>
<tr class="odd">
<td>0.5</td>
<td align="right">1.051</td>
<td align="right">0.007</td>
<td align="right">0.574</td>
<td align="right">1.000</td>
<td align="right">1.052</td>
<td align="right">1.053</td>
</tr>
<tr class="even">
<td>0.84</td>
<td align="right">1.776</td>
<td align="right">0.021</td>
<td align="right">0.903</td>
<td align="right">1.535</td>
<td align="right">1.790</td>
<td align="right">1.800</td>
</tr>
<tr class="odd">
<td>0.9</td>
<td align="right">2.093</td>
<td align="right">0.033</td>
<td align="right">0.952</td>
<td align="right">1.689</td>
<td align="right">2.118</td>
<td align="right">2.128</td>
</tr>
<tr class="even">
<td>0.95</td>
<td align="right">2.572</td>
<td align="right">0.053</td>
<td align="right">0.985</td>
<td align="right">1.884</td>
<td align="right">2.659</td>
<td align="right">2.655</td>
</tr>
<tr class="odd">
<td>0.975</td>
<td align="right">3.095</td>
<td align="right">0.091</td>
<td align="right">0.996</td>
<td align="right">2.054</td>
<td align="right">3.302</td>
<td align="right">3.247</td>
</tr>
</tbody>
</table>
<p>Clearly the bca limits match the exact values very well and suggests a large upward correction to the standard limits. Here the corrections are all positive as seen in the table below; <span class="math inline">\(\hat{z}_0 = 0.093\)</span> and <span class="math inline">\(\hat{a} = 0.092\)</span>.</p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb23-1" data-line-number="1">knitr<span class="op">::</span><span class="kw"><a href="http://www.rdocumentation.org/packages/knitr/topics/kable">kable</a></span>(result<span class="op">$</span>stats, <span class="dt">digits =</span> <span class="dv">3</span>)</a></code></pre></div>
<table class="table">
<thead><tr class="header">
<th></th>
<th align="right">theta</th>
<th align="right">sd</th>
<th align="right">a</th>
<th align="right">az</th>
<th align="right">z0</th>
<th align="right">A</th>
<th align="right">sdd</th>
<th align="right">mean</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>est</td>
<td align="right">1</td>
<td align="right">0.538</td>
<td align="right">0.092</td>
<td align="right">0.088</td>
<td align="right">0.093</td>
<td align="right">0.496</td>
<td align="right">0.503</td>
<td align="right">1.054</td>
</tr>
<tr class="even">
<td>jsd</td>
<td align="right">0</td>
<td align="right">0.004</td>
<td align="right">0.004</td>
<td align="right">0.005</td>
<td align="right">0.010</td>
<td align="right">0.020</td>
<td align="right">0.003</td>
<td align="right">0.004</td>
</tr>
</tbody>
</table>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb24-1" data-line-number="1">knitr<span class="op">::</span><span class="kw"><a href="http://www.rdocumentation.org/packages/knitr/topics/kable">kable</a></span>(result<span class="op">$</span>abcstats, <span class="dt">digits =</span> <span class="dv">3</span>)</a></code></pre></div>
<table class="table">
<thead><tr class="header">
<th></th>
<th align="right">x</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>a</td>
<td align="right">0.094</td>
</tr>
<tr class="even">
<td>z0</td>
<td align="right">0.094</td>
</tr>
</tbody>
</table>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb25-1" data-line-number="1">knitr<span class="op">::</span><span class="kw"><a href="http://www.rdocumentation.org/packages/knitr/topics/kable">kable</a></span>(result<span class="op">$</span>ustats, <span class="dt">digits =</span> <span class="dv">3</span>)</a></code></pre></div>
<table class="table">
<thead><tr class="header">
<th></th>
<th align="right">ustat</th>
<th align="right">sdu</th>
<th align="right">B</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>est</td>
<td align="right">0.946</td>
<td align="right">0.487</td>
<td align="right">16000</td>
</tr>
<tr class="even">
<td>jsd</td>
<td align="right">0.004</td>
<td align="right">0.004</td>
<td align="right">0</td>
</tr>
</tbody>
</table>
<p>The plot below shows that there is moderate amount of internal error in <span class="math inline">\(\hat{\theta}_{bca}(0.975)\)</span> as shown by the red bar. The <code>pct</code> column suggests why: <span class="math inline">\(\hat{\theta}_{bca}(0.975)\)</span> occurs at the <span class="math inline">\(0.996\)</span>-quantile of the 16,000 replications, i.e., at the 64th largest <span class="math inline">\(\hat{\theta}\)</span>, where there is a limited amount of data for estimating the distribution.</p>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb26-1" data-line-number="1"><span class="kw"><a href="../reference/bcaplot.html">bcaplot</a></span>(result)</a></code></pre></div>
<p><img src="bcaboot_files/figure-html/unnamed-chunk-27-1.png" width="700"></p>
</div>
<div id="references" class="section level2 unnumbered">
<h2 class="hasAnchor">
<a href="#references" class="anchor"></a>References</h2>
<div id="refs" class="references">
<div id="ref-diciccio1992">
<p>DiCiccio, Thomas, and Bradley Efron. 1992. “More Accurate Confidence Intervals in Exponential Families.” <em>Biometrika</em> 79 (2). [Oxford University Press, Biometrika Trust]: 231–45. <a href="http://www.jstor.org/stable/2336835" class="uri">http://www.jstor.org/stable/2336835</a>.</p>
</div>
<div id="ref-diciccio1996">
<p>DiCiccio, Thomas J., and Bradley Efron. 1996. “Bootstrap Confidence Intervals.” <em>Statist. Sci.</em> 11 (3). The Institute of Mathematical Statistics: 189–228. <a href="https://doi.org/10.1214/ss/1032280214" class="uri">https://doi.org/10.1214/ss/1032280214</a>.</p>
</div>
<div id="ref-efron1987">
<p>Efron, Bradley. 1987. “Better Bootstrap Confidence Intervals.” <em>Journal of the American Statistical Association</em> 82 (397). [American Statistical Association, Taylor &amp; Francis, Ltd.]: 171–85. <a href="http://www.jstor.org/stable/2289144" class="uri">http://www.jstor.org/stable/2289144</a>.</p>
</div>
<div id="ref-efron2016">
<p>Efron, Bradley, and Trevor Hastie. 2016. <em>Computer Age Statistical Inference: Algorithms, Evidence, and Data Science</em>. 1st ed. New York, NY, USA: Cambridge University Press.</p>
</div>
<div id="ref-efronnaras2018">
<p>Efron, Bradley, and Balasubramanian Narasimhan. 2018. “The Automatic Construction of Bootstrap Confidence Intervals.”</p>
</div>
</div>
</div>
  </div>

  <div class="col-md-3 hidden-xs hidden-sm" id="sidebar">
        <div id="tocnav">
      <h2 class="hasAnchor">
<a href="#tocnav" class="anchor"></a>Contents</h2>
      <ul class="nav nav-pills nav-stacked">
<li><a href="#introduction">Introduction</a></li>
      <li><a href="#a-nonparametric-example">A Nonparametric Example</a></li>
      <li><a href="#a-parametric-example">A Parametric Example</a></li>
      <li><a href="#ratio-of-independent-variance-estimates">Ratio of Independent Variance Estimates</a></li>
      <li><a href="#references">References</a></li>
      </ul>
</div>
      </div>

</div>


      <footer><div class="copyright">
  <p>Developed by <a href="https://efron.web.stanford.edu">Bradley Efron</a>, <a href="https://statistics.stanford.edu/people/balasubramanian-narasimhan">Balasubramanian Narasimhan</a>.</p>
</div>

<div class="pkgdown">
  <p>Site built with <a href="http://pkgdown.r-lib.org/">pkgdown</a>.</p>
</div>

      </footer>
</div>

  

  </body>
</html>
